apps/academico/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
   url(r'^alumnos_uni/$', views.Listar_alumnos_uni.as_view(), name="listar_alumnos_uni"),
   url(r'^alumnos_uni/agregar/$', views.Registrar_persona_alumno.as_view(), name="agregar_persona"),
   url(r'^alumnos_uni/agregar_alumno/(?P<pk>\d+)/$', views.Registrar_alumno.as_view(), name="agregar_alumno"),
   url(r'^alumnos_uni/actualizar_alumno/(?P<pk>\d+)/$', views.Actualizar_alumno.as_view(), name="actualizar_alumno"),
   url(r'^periodos/$', views.Listar_periodos.as_view(), name="listar_periodos"),
   url(r'^planes_academicos/$', views.Listar_planes_academicos.as_view(), name="listar_planes_academicos"),
   url(r'^planes_academicos_cursos/$', views.BusquedaPlan_acad_curso),
   url(r'^planes_academicos_cursos/agregar/$', views.Nuevo_plan_acad_curso, name="lista_agregar_plan_curso"),
   url(r'^planes_academicos_cursos/buscar_facultad/', views.Buscar_facultad),
   url(r'^planes_academicos_cursos/buscar_escuela/', views.Buscar_escuela),
   url(r'^planes_academicos_cursos/buscar_plan_acad/', views.Buscar_plan_acad),
   url(r'^planes_academicos_cursos/buscar_plan_acad_cursos/', views.Listado_plan_acad_cursos),
   url(r'^planes_academicos_cursos/nuevo_plan_curso/', views.Nuevo_plan_curso),
   url(r'^planes_academicos_cursos/buscar_curso_plan/', views.Buscar_curso_plan),
   url(r'^planes_academicos_cursos/agregar_plan_acad_curso/', views.Agregar_plan_acad_curso2),
   url(r'^planes_academicos_cursos/buscar_pre_requisito/', views.Buscar_pre_requisito),
   url(r'^planes_academicos_cursos/eliminar_plan_acad_curso/', views.Eliminar_plan_acad_curso),
   url(r'^planes_academicos_cursos/nuevo_curso/', views.Nuevo_curso),
   url(r'^planes_academicos_cursos/guardar_curso/', views.Guardar_curso),
   url(r'^planes_academicos_cursos/editar_plan_curso/', views.Editar_plan_curso),

   ]

universidad/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     #INICIO UPEU
    url(r'^upeu/', include('apps.upeu.urls')),
    url(r'^admision/', include('apps.admision.urls')),
    url(r'^academico/', include('apps.academico.urls')),
    url(r'^$', include('apps.upeu.urls'))
]

apps/academico/models.py
from django.db import models
from apps.upeu.models import Entidad_academica

# Create your models here.
class Persona(models.Model):
	nombre = models.CharField("Nombre", max_length=60, help_text="Nombre")
	nombres = models.CharField("Nombres", max_length=120, null=True, blank=True, help_text="Otros nombres")
	apepat = models.CharField("Apellido paterno", max_length=120)
	apemat = models.CharField("Apellido materno", max_length=120)
	fecha_nac = models.DateField("Fecha de nacimiento")
	sexo = models.CharField("Sexo", max_length=1)
	direccion = models.CharField("Dirección actual", max_length=200, null=True, blank=True)
	celular = models.CharField("Celular", max_length=12, null=True, blank=True)
	estado = models.CharField("Estado", max_length=1)
	fecha_hora_registro = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s %s %s %s" % (self.apepat, self.apemat, self.nombre, self.nombres)

class Alumno_uni(models.Model):
	alumno = models.OneToOneField(Persona, primary_key=True)
	codigo_universitario = models.CharField("Código universitario", max_length=12, null=True, blank=True, unique=True)
	estado = models.CharField("Estado", max_length=1)
	
	def __str__(self):
		return self.codigo_universitario

class Periodo(models.Model):
	nombre_periodo = models.CharField("Nombre del periodo", max_length=30, unique=True)
	fecha_inicio = models.DateField("Fecha de inicio")
	fecha_final = models.DateField("Fecha final")
	abierto = models.CharField("Abierto", max_length=1, help_text="Use 1 parar abierto, 0 para cerrado")
	estado = models.CharField("Estado", max_length=1)
	
	def __str__(self):
		return self.nombre_periodo

class Plan_academico(models.Model):
	numero_plan = models.CharField("Número de plan", max_length=60, null=True, blank=True, unique=True)
	entidad_academica = models.ForeignKey(Entidad_academica, help_text="Escuela profesional o entidad académica")
	periodo = models.ForeignKey(Periodo, help_text="Periodo académico")
	estado = models.CharField("Estado", max_length=1)
	
	def __str__(self):
		return self.numero_plan

class Ciclo(models.Model):
	numero = models.DecimalField("Número", max_digits=2, decimal_places=0, unique=True)
	numero_letras = models.CharField("Número en letra", max_length=20, null=True, blank=True, unique=True)
	numero_romano = models.CharField("Número en romano", max_length=4, null=True, blank=True, unique=True)
	estado = models.CharField("Estado", max_length=1)

	def __str__(self):
		return "%s" % (self.numero)

class Area(models.Model):
	nombre_area = models.CharField("Nombre del área", max_length=100, unique=True)
	descripcion = models.CharField(max_length=200, null=True, blank=True)
	estado = models.CharField("Estado", max_length=1)

	def __str__(self):
		return self.nombre_area

class Curso(models.Model):
	nombre_curso = models.CharField("Nombre del curso", max_length=200)
	abreviatura = models.CharField("Abreviatura del curso", max_length=30, null=True, blank=True)
	area = models.ForeignKey(Area)
	estado = models.CharField("Estado", max_length=1)

	class Meta:
		unique_together = (('nombre_curso', 'area'),)

	def __str__(self):
		return self.nombre_curso

class Plan_acad_curso(models.Model):
	plan_academico = models.ForeignKey(Plan_academico)
	ciclo = models.ForeignKey(Ciclo)
	curso = models.ForeignKey(Curso)
	creditos = models.DecimalField("Número de créditos", max_digits=4, decimal_places=0)
	thp = models.DecimalField("THP", max_digits=4, decimal_places=0)
	hnp = models.DecimalField("HNP", max_digits=4, decimal_places=0)
	pre_requisito = models.ForeignKey('self', null=True, blank=True, help_text="Curso pre-requisito")
	estado = models.CharField("Estado", max_length=1)

	class Meta:
		unique_together = (('plan_academico', 'ciclo','curso'),)

	def __str__(self):
		return "%s (%s) %s" % (self.plan_academico, self.ciclo, self.curso)

apps/academico/forms.py
from django import forms
# from .models import Persona

# 	class PersonaForm(forms.ModelForm):
# 		class Meta:
# 			model = Persona
# 		    fields = ["nombre"]

# 		def clean_nombre(self):
# 			nombre = self.cleaned_data.get("nombre")

# 			if not nombre == "Persy"
# 				raise.forms.ValidationError("Por favor ingresel nombre Persy jejej")


# 			return nombre

apps/academico/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from .models import Alumno_uni, Persona, Alumno_uni, Periodo, Plan_academico, Plan_acad_curso, Ciclo, Curso, Area
from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.db.models import Count, Sum, F, Q
from apps.upeu.models import Entidad_academica

# Create your views here.
class Listar_alumnos_uni(ListView):
	template_name='academico/alumno_uni/index.html'
	model= Alumno_uni
	context_object_name = 'alumnos_uni'

class Registrar_persona1(CreateView):
	template_name='academico/alumno_uni/form_new.html'
	model = Persona
	fields = ['nombre','nombres','apepat','apemat','fecha_nac','sexo','direccion','celular','estado']
	def get_success_url(self):
		return reverse('agregar_alumno', kwargs={'pk': self.object.pk})

class Registrar_persona_alumno(CreateView):
	template_name='academico/alumno_uni/form_new.html'
	model = Persona
	fields = ['nombre','nombres','apepat','apemat','fecha_nac','sexo','direccion','celular','estado']
	def get_success_url(self):
		print ("Hola a todos")
		alu = Alumno_uni(alumno_id=self.object.pk,
								estado='1')
		alu.save()

		return reverse('actualizar_alumno', kwargs={'pk': self.object.pk})

class Registrar_alumno(CreateView):
	template_name='academico/alumno_uni/form_new_alumno.html'
	model = Alumno_uni
	fields = ['alumno', 'codigo_universitario','estado']
	success_url = reverse_lazy('listar_alumnos_uni')


class Actualizar_alumno(UpdateView):
	template_name = 'academico/alumno_uni/form_new_alumno.html'
	model = Alumno_uni
	fields = ['codigo_universitario','estado']
	success_url = reverse_lazy('listar_alumnos_uni')

class Listar_periodos(ListView):
	template_name='academico/periodo/index.html'
	model= Periodo
	context_object_name = 'periodos'

class Listar_planes_academicos(ListView):
	template_name='academico/plan_academico/index.html'
	model= Plan_academico
	context_object_name = 'planes_academicos'

def BusquedaPlan_acad_curso(request):
	hola = "Hola  a todos"
	if request.method == 'POST':
		plan_academico = request.POST['plan_academico']
		
	else:
		plan_academico = '0'


	planes_academicos = Plan_academico.objects.all()
	planes_acad_cursos = Plan_acad_curso.objects.filter(plan_academico=plan_academico).annotate(total_horas=F('thp') + F('hnp')).order_by('ciclo')
	
	ciclos = Ciclo.objects.filter(id__in=Plan_acad_curso.objects.values('ciclo_id').distinct().filter(plan_academico=plan_academico)).order_by('numero')

	context = {'ciclos':ciclos, 'plan_academico':plan_academico, 'planes_acad_cursos':planes_acad_cursos, 'hola':hola, 'planes_academicos':planes_academicos}
	
	return render_to_response('academico/plan_acad_curso/index.html', context, context_instance=RequestContext(request))

def Nuevo_plan_acad_curso(request):
	list_ent_univers = Entidad_academica.objects.filter(tipo_entidad=1).order_by('tipo_entidad')

	context = {'list_ent_univers':list_ent_univers}
	#return render(request,'upeu/index.html')
	return render(request, 'academico/plan_acad_curso/form_new.html', context)

def Buscar_facultad(request):
	if request.GET:
		id_univers = request.GET['id_univers']
		list_ent_facultades = Entidad_academica.objects.filter(tipo_entidad=2, entidad_padre=id_univers).order_by('nombre_entidad')
		context = {'list_ent_facultades':list_ent_facultades}
		return render(request, 'academico/plan_acad_curso/busq/busq_facultad.html',context)
	else:
		return render(request, 'academico/plan_acad_curso/busq/busq_facultad.html')

def Buscar_escuela(request):
	if request.GET:
		id_facultad = request.GET['id_facultad']
		list_ent_escuelas = Entidad_academica.objects.filter(tipo_entidad=3, entidad_padre=id_facultad).order_by('nombre_entidad')
		context = {'list_ent_escuelas':list_ent_escuelas}
		return render(request, 'academico/plan_acad_curso/busq/busq_escuela.html',context)
	else:
		return render(request, 'academico/plan_acad_curso/busq/busq_escuela.html')

def Buscar_plan_acad(request):
	if request.GET:
		id_escuela = request.GET['id_escuela']
		list_planes_acad = Plan_academico.objects.filter(entidad_academica=id_escuela)
		context = {'list_planes_acad':list_planes_acad}
		return render(request, 'academico/plan_acad_curso/busq/busq_plan_acad.html',context)
	else:
		return render(request, 'academico/plan_acad_curso/busq/busq_plan_acad.html')

def Listado_plan_acad_cursos(request):
	if request.GET:
		plan_academico = request.GET['id_plan_academico']
		
	else:
		plan_academico = '0'


	planes_acad_cursos = Plan_acad_curso.objects.filter(plan_academico=plan_academico).annotate(total_horas=F('thp') + F('hnp')).order_by('ciclo')
	
	ciclos = Ciclo.objects.filter(id__in=Plan_acad_curso.objects.values('ciclo_id').distinct().filter(plan_academico=plan_academico)).order_by('numero')

	context = {'ciclos':ciclos, 'planes_acad_cursos':planes_acad_cursos}
	
	return render(request, 'academico/plan_acad_curso/busq/busq_plan_acad_cursos.html',context)
	
	

def Nuevo_plan_curso(request):
	if request.GET:
		id_plan_academico = request.GET['id_plan_academico']
		
		lista_ciclos = Ciclo.objects.all().order_by('numero')
		plan_academico = Plan_academico.objects.filter(id=id_plan_academico)
		
		#planes_acad_cursos = Plan_acad_curso.objects.filter(plan_academico=id_plan_academico).annotate(total_horas=F('thp') + F('hnp')).order_by('ciclo')
		#ciclos = Ciclo.objects.filter(id__in=Plan_acad_curso.objects.values('ciclo_id').distinct().filter(plan_academico=id_plan_academico)).order_by('numero')

		context = {'lista_ciclos':lista_ciclos, 'plan_academico':plan_academico}

		return render(request, 'academico/plan_acad_curso/form_new_plan_curso.html',context)
	else:
		return render(request, 'academico/plan_acad_curso/form_new_plan_curso.html')


def Buscar_curso_plan(request):
	if request.GET:
		buscar = request.GET['buscar']
		plan_academico = request.GET['plan_academico']
		print (buscar)
		lista_cursos = Curso.objects.filter(nombre_curso__icontains=buscar).exclude(id__in=Plan_acad_curso.objects.values('curso_id').distinct().filter(plan_academico=plan_academico)).order_by('nombre_curso')[:8]
		context = {'Hola':"123", 'lista_cursos':lista_cursos}

		return render(request, 'academico/plan_acad_curso/busq/busq_curso.html',context)
	else:
		return render(request, 'academico/plan_acad_curso/busq_curso.html')

def Agregar_plan_acad_curso(request):
	if request.method == 'POST':
		plan_academico = request.POST['plan_academico']
		ciclo = request.POST['ciclo']
		curso = request.POST['curso']
		creditos = request.POST['creditos']
		thp = request.POST['thp']
		hnp = request.POST['hnp']
		pre_requisito = request.POST['pre_requisito']
		
		p = Plan_acad_curso(plan_academico_id=plan_academico,
								ciclo_id=ciclo,
								curso_id=curso,
								creditos=creditos,
								thp=thp,
								hnp=hnp,
								pre_requisito_id=pre_requisito,
								estado='1')
		p.save()
		if p.save:
			resultado = "Registrado correctamente"
			list_ent_univers = Entidad_academica.objects.filter(tipo_entidad=1).order_by('tipo_entidad')
			context = {'resultado':resultado, 'list_ent_univers':list_ent_univers}
			return render(request, 'academico/plan_acad_curso/form_new.html', context)
		
		else:
			resultado = "No se pudo registrar"
			context = {'resultado':resultado}
			return render(request, 'academico/plan_acad_curso/form_new.html', context)	

	else:
		resultado = "No envió un método POST"
		context = {'resultado':resultado}
		return reverse(request, 'academico/plan_acad_curso/form_new.html', context)

def Agregar_plan_acad_curso2(request):
	if request.method == 'GET':
		plan_academico = request.GET['plan_academico']
		ciclo = request.GET['ciclo']
		curso = request.GET['curso']
		creditos = request.GET['creditos']
		thp = request.GET['thp']
		hnp = request.GET['hnp']
		pre_requisito = request.GET['pre_requisito']
		try:
			p = Plan_acad_curso(plan_academico_id=plan_academico,
								ciclo_id=ciclo,
								curso_id=curso,
								creditos=creditos,
								thp=thp,
								hnp=hnp,
								pre_requisito_id=pre_requisito,
								estado='1')
			p.save()
			#if p.save:
			resultado = "Registrado correctamente"
			context = {'resultado':resultado}
			return render(request, 'academico/plan_acad_curso/busq/resultado_agregar_plan_curso.html', context)
		
		except:
			resultado = "No se pudo registrar, ingrese todos los datos requeridos, no duplique un curso existente"
			context = {'resultado':resultado}
			return render(request, 'academico/plan_acad_curso/busq/resultado_agregar_plan_curso.html', context)	

	else:
		resultado = "No envió un método POST"
		context = {'resultado':resultado}
		return reverse(request, 'academico/plan_acad_curso/busq/resultado_agregar_plan_curso.html', context)


def Buscar_pre_requisito(request):
	if request.GET:
		id_plan_academico = request.GET['id_plan_academico']
		buscar = request.GET['buscar']
		ciclo = int(request.GET['ciclo'])
		# Para mayores se usa __gt (>) y para menor:__lt
		planes_acad_cursos = Plan_acad_curso.objects.filter(plan_academico=id_plan_academico, curso__nombre_curso__icontains=buscar, 
															ciclo_id__lt=ciclo).order_by('curso')

		context = {'planes_acad_cursos':planes_acad_cursos}

		return render(request, 'academico/plan_acad_curso/busq/busq_pre_requisito.html',context)
	else:
		return render(request, 'academico/plan_acad_curso/busq/busq_pre_requisito.html')

def Eliminar_plan_acad_curso(request):
	if request.GET:
		academico_plan_acad_curso = request.GET['academico_plan_acad_curso']
		try:
			plan = Plan_acad_curso.objects.get(pk=academico_plan_acad_curso)
			plan.delete()

			resultado = "Eliminado correctamente"
			context = {'resultado':resultado}
			return render(request, 'academico/plan_acad_curso/busq/resul_eliminar_curso.html', context)

		except:

templates/academico/alumno_uni/form_new.html
{% extends "upeu/superior.html" %}
{% block content %}
 {% load staticfiles %}
  <main>
        <div class="section" id="index-banner">
          <div class="container">
            <div class="row center">
              <div class="col s12 m12">
                  <font size="4"><b>Registro de alumnos</b></font>
               </div>
            </div>
          </div>
        </div>
        <div class="github-commit">
                <div class="container">
                        <div class="commit">Nuevo alumno</b> &nbsp;&nbsp;

                            <a class='dropdown-button btn-flat right grey-text text-lighten-5 waves-effect waves-light hide-on-small-only' href='#' data-activates='dropdown1'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Opciones &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
                                <ul id='dropdown1' class='dropdown-content'>
                                <li><a href="agregar/"><i class="material-icons dp8">note_add</i> Nuevo alumno</a></li>
                                <li><a class="modal-trigger" href="#modal1" onclick="ver_impresion()"><i class="material-icons dp48">print</i> Informe</a></li>
                            </ul>
                        </div>
                    </div>
                    </div>

         <div class="card-panel">
        <form method="POST" role="form" autocomplete="off" name="form">
           {% csrf_token %}
        	<div class="row">
    			<div class="input-field col s12 m3">
      				 <i class="material-icons prefix">account_circle</i>
                    <label class="active" for="{{ form.nombre.id_for_label }}">Nombre</label>
                   	{{form.nombre}}
    			</div>
                <div class="input-field col s12 m3">
                    <label class="active" for="{{ form.nombres.id_for_label }}">Nombres</label>
                        {{form.nombres}}
                </div>
                <div class="input-field col s12 m3">
                    <label class="active" for="{{ form.apepat.id_for_label }}">Apellido paterno</label>
                        {{form.apepat}}
                </div>
                <div class="input-field col s12 m3">
                    <label class="active" for="{{ form.apemat.id_for_label }}">Apellido materno</label>
                        {{form.apemat}}
                </div>
    		</div>
            <div class="row">
                <div class="input-field col s12 m3">
                    <label class="active" for="{{ form.fecha_nac.id_for_label }}">Fecha de nacimiento</label>
                    <input id="id_fecha_nac" name="fecha_nac" type="text" value="{{form.fecha_nac.value}}" class="datepicker">
                        
                </div>
                 <div class="input-field col s12 m3">
                    <label class="active" for="{{ form.sexo.id_for_label }}">Sexo</label>
                    <input name="sexo" type="radio" id="id_masc" value="M" checked="" class="with-gap"/>
                        <label for="id_masc">Masculino</label>
                    <input name="sexo" type="radio" id="id_fem" value="F" class="with-gap"/>
                        <label for="id_fem">Femenino</label>
                </div>
                <div class="input-field col s12 m6">
                    <i class="material-icons prefix">room</i>
                    <label class="active" for="{{ form.direccion.id_for_label }}">Dirección actual</label>
                          {{form.direccion}}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12 m3">
                     <i class="material-icons prefix">phonelink_ring</i>
                    <label class="active" for="{{ form.celular.id_for_label }}">Celular</label>
                         {{form.celular}}
                </div>
                <div class="input-field col s12 m9">
                    <label class="active" for="{{ form.estado.id_for_label }}">Estado</label>
                    <input name="estado" type="radio" id="activo" value="1" checked="" class="with-gap"/>
                        <label for="activo">Activo</label>
                    <input name="estado" type="radio" id="desactivo" value="0" class="with-gap"/>
                        <label for="desactivo">Desactivo</label>
                </div>
            </div>
    		<div class="row">
    			<div class="input-field col s12 m12">
      				<input type="submit" name="opcion" value="Registar" class="waves-effect waves-light btn"/>
					<a href="../" class="waves-effect waves-light btn">Cancelar</a>
    			</div>
    		</div>
    	</form>
    </div>
    </main>
    <script type="text/javascript">
        document.form.sexo.value='{{form.sexo.value}}';
        document.form.estado.value='{{form.estado.value}}';
        var fecha_nac='{{form.fecha_nac.value}}';
        var id='{{form.id.value}}';
        if (fecha_nac =='None')
        {
          document.form.fecha_nac.value='';
        }
        if (id !='')
        {
            document.form.opcion.value='Actualizar';
        }
    </script>
    <!--  Scripts-->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
        $('.datepicker').pickadate({
            monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
            weekdaysFull: [ 'Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado' ],
            weekdaysLetter: [ 'D', 'L', 'M', 'M', 'J', 'V', 'S' ],
            today: 'Hoy',
            clear: 'Limpiar',
            close: 'Cerrar',
            selectMonths: true, // Creates a dropdown to control month
            selectYears: 15, // Creates a dropdown of 15 years to control year
            format: 'dd/mm/yyyy'    
         });
        })
    </script>
    <script>if (!window.jQuery) { document.write('<script src="bin/jquery-2.1.1.min.js"><\/script>'); }
    </script>
    <script src="{% static "js/jquery.timeago.min.js" %}"></script>
    <script src="{% static "js/prism.js" %}"></script>
    <script src="{% static "jade/lunr.min.js" %}"></script>
    <script src="{% static "jade/search.js" %}"></script>
    <script src="{% static "bin/materialize.js" %}"></script>
    <script src="{% static "js/init.js" %}"></script>
    <!-- Twitter Button -->
    <script src="https://apis.google.com/js/platform.js" async defer></script>
          {% endblock %}
</body>
</html>

templates/academico/alumno_uni/form_new_alumno.html
{% extends "upeu/superior.html" %}
{% block content %}
  <main>
        <div class="section" id="index-banner">
          <div class="container">
            <div class="row center">
              <div class="col s12 m12">
                  <font size="4"><b>Registro de alumnos</b></font>
               </div>
            </div>
          </div>
        </div>
        <div class="github-commit">
                <div class="container">
                        <div class="commit"><b>Para terminar...</b> &nbsp;&nbsp;

                            <a class='dropdown-button btn-flat right grey-text text-lighten-5 waves-effect waves-light hide-on-small-only' href='#' data-activates='dropdown1'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Opciones &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
                                <ul id='dropdown1' class='dropdown-content'>
                                <li><a href="agregar/"><i class="material-icons dp8">note_add</i> Nuevo alumno</a></li>
                                <li><a class="modal-trigger" href="#modal1" onclick="ver_impresion()"><i class="material-icons dp48">print</i> Informe</a></li>
                            </ul>
                        </div>
                    </div>
                    </div>

    	 <div class="card-panel">
        <form method="POST" role="form" autocomplete="off" name="form">
           {% csrf_token %}
          <div class="row">
                <div class="input-field col s12 m6">
                    <label class="active" for="{{ form.codigo_universitario.id_for_label }}">Código universitario</label>
                         {{form.codigo_universitario}}
               </div>
                <div class="input-field col s12 m6">
                    <label class="active" for="{{ form.estado.id_for_label }}">Estado</label>
                    <input name="estado" type="radio" id="activo" value="1" checked="" class="with-gap"/>
                        <label for="activo">Activo</label>
                    <input name="estado" type="radio" id="desactivo" value="0" class="with-gap"/>
                        <label for="desactivo">Desactivo</label>

                </div>
            </div>
    		<div class="row">
    			<div class="input-field col s12 m12">
      				<input type="submit" name="opcion" value="Aceptar" class="waves-effect waves-light btn"/>
					</div>
    		</div>
    	</form>
    </div>
    </main>
    <script type="text/javascript">
        document.form.estado.value='{{form.estado.value}}';
    </script>
           {% endblock %}
</body>
</html>