universidad/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     #INICIO UPEU
    url(r'^upeu/', include('apps.upeu.urls')),
    url(r'^admision/', include('apps.admision.urls')),
    url(r'^academico/', include('apps.academico.urls')),
    url(r'^$', include('apps.upeu.urls'))
]

apps/academico/models.py
from django.db import models
from apps.upeu.models import Entidad_academica

# Create your models here.
class Persona(models.Model):
	nombre = models.CharField("Nombre", max_length=60, help_text="Nombre")
	nombres = models.CharField("Nombres", max_length=120, null=True, blank=True, help_text="Otros nombres")
	apepat = models.CharField("Apellido paterno", max_length=120)
	apemat = models.CharField("Apellido materno", max_length=120)
	fecha_nac = models.DateField("Fecha de nacimiento")
	sexo = models.CharField("Sexo", max_length=1)
	direccion = models.CharField("Dirección actual", max_length=200, null=True, blank=True)
	celular = models.CharField("Celular", max_length=12, null=True, blank=True)
	estado = models.CharField("Estado", max_length=1)
	fecha_hora_registro = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s %s %s %s" % (self.apepat, self.apemat, self.nombre, self.nombres)

class Alumno_uni(models.Model):
	alumno = models.OneToOneField(Persona, primary_key=True)
	codigo_universitario = models.CharField("Código universitario", max_length=12, null=True, blank=True, unique=True)
	estado = models.CharField("Estado", max_length=1)
	
	def __str__(self):
		return self.codigo_universitario

class Periodo(models.Model):
	nombre_periodo = models.CharField("Nombre del periodo", max_length=30, unique=True)
	fecha_inicio = models.DateField("Fecha de inicio")
	fecha_final = models.DateField("Fecha final")
	abierto = models.CharField("Abierto", max_length=1, help_text="Use 1 parar abierto, 0 para cerrado")
	estado = models.CharField("Estado", max_length=1)
	
	def __str__(self):
		return self.nombre_periodo

class Plan_academico(models.Model):
	numero_plan = models.CharField("Número de plan", max_length=60, null=True, blank=True, unique=True)
	entidad_academica = models.ForeignKey(Entidad_academica, help_text="Escuela profesional o entidad académica")
	periodo = models.ForeignKey(Periodo, help_text="Periodo académico")
	estado = models.CharField("Estado", max_length=1)
	
	def __str__(self):
		return self.numero_plan

class Ciclo(models.Model):
	numero = models.DecimalField("Número", max_digits=2, decimal_places=0, unique=True)
	numero_letras = models.CharField("Número en letra", max_length=20, null=True, blank=True, unique=True)
	numero_romano = models.CharField("Número en romano", max_length=4, null=True, blank=True, unique=True)
	estado = models.CharField("Estado", max_length=1)

	def __str__(self):
		return "%s" % (self.numero)

class Area(models.Model):
	nombre_area = models.CharField("Nombre del área", max_length=100, unique=True)
	descripcion = models.CharField(max_length=200, null=True, blank=True)
	estado = models.CharField("Estado", max_length=1)

	def __str__(self):
		return self.nombre_area

class Curso(models.Model):
	nombre_curso = models.CharField("Nombre del curso", max_length=200)
	abreviatura = models.CharField("Abreviatura del curso", max_length=30, null=True, blank=True)
	area = models.ForeignKey(Area)
	estado = models.CharField("Estado", max_length=1)

	class Meta:
		unique_together = (('nombre_curso', 'area'),)

	def __str__(self):
		return self.nombre_curso

class Plan_acad_curso(models.Model):
	plan_academico = models.ForeignKey(Plan_academico)
	ciclo = models.ForeignKey(Ciclo)
	curso = models.ForeignKey(Curso)
	creditos = models.DecimalField("Número de créditos", max_digits=4, decimal_places=0)
	thp = models.DecimalField("THP", max_digits=4, decimal_places=0)
	hnp = models.DecimalField("HNP", max_digits=4, decimal_places=0)
	pre_requisito = models.ForeignKey('self', null=True, blank=True, help_text="Curso pre-requisito")
	estado = models.CharField("Estado", max_length=1)

	class Meta:
		unique_together = (('plan_academico', 'ciclo','curso'),)

	def __str__(self):
		return "%s (%s) %s" % (self.plan_academico, self.ciclo, self.curso)

templates/academico/plan_acad_curso/busq/busq_curso.html
<div class="collection">
	{% for cur in lista_cursos %}
    <a href="javascript:void(0);" class="collection-item"  onclick="Seleccionar_curso('{{ cur.id }}','{{ cur.nombre_curso }}');">{{ cur.nombre_curso }}<span class="badge"><font size="1">{{ cur.area }}</font></span></a>
    {% endfor %}
</div>

templates/academico/plan_acad_curso/busq/busq_escuela.html
{% load staticfiles %}
<select id="id_escuela" name="id_escuela" required="">
	<option value="">Seleccione--</option>
	{% for esc in list_ent_escuelas %}
	<option value="{{ esc.id }}"> {{ esc.tipo_entidad.abreviatura }} {{ esc.tipo_entidad.conector|upper }} {{ esc.nombre_entidad }}</option>
	{% endfor %}
</select>
<script src="{% static "js/init.js" %}"></script>
<script type="text/javascript">
        $(document).ready(function() {
           $("#id_escuela").change(function() {
                var id_escuela = $(this).val();
                if (id_escuela != '') {
                    $("#resul_plan_acad").load("../buscar_plan_acad/?id_escuela="+id_escuela, "", function() {
                        $("#resul_plan_acad").show("slow");
                    });
                } else {
                    $("#resul_plan_acad").hide("slow");
                    $("#resul_plan_acad_cursos").hide("slow");
                    $("#boton_agregar").hide("slow");  
                 }
            });
        });
  </script>

templates/academico/plan_acad_curso/busq/busq_facultad.html
{% load staticfiles %}
<select id="id_facultad" name="id_facultad" required="">
	<option value="">Seleccione--</option>
	{% for fac in list_ent_facultades %}
	<option value="{{ fac.id }}"> {{ fac.tipo_entidad }} {{ fac.tipo_entidad.conector|upper }} {{ fac.nombre_entidad }}</option>
	{% endfor %}
</select>

<script src="{% static "js/init.js" %}"></script>
<script type="text/javascript">
        $(document).ready(function() {
           $("#id_facultad").change(function() {
                var id_facultad = $(this).val();
                if (id_facultad != '') {
                    $("#resul_escuela").load("../buscar_escuela/?id_facultad="+id_facultad, "", function() {
                        $("#resul_escuela").show("slow");
                    });
                } else {
                    $("#resul_escuela").hide("slow");
                     $("#resul_plan_acad").hide("slow");
                     $("#resul_plan_acad_cursos").hide("slow");
                     $("#boton_agregar").hide("slow");  
                 }
            });
        });
  </script>

templates/academico/plan_acad_curso/busq/busq_plan_acad.html
{% load staticfiles %}
<select id="id_plan_academico" name="id_plan_acad" required="">
	<option value="">Seleccione--</option>
	{% for plan in list_planes_acad %}
	<option value="{{ plan.id }}">{{ plan.numero_plan }}</option>
	{% endfor %}
</select>
<script src="{% static "js/init.js" %}"></script>

<script type="text/javascript">
        $(document).ready(function() {
           $("#id_plan_academico").change(function() {
                var id_plan_academico = $(this).val();
                if (id_plan_academico != '') {
                    $("#resul_plan_acad_cursos").show("slow");
                    $("#resul_plan_acad_cursos").load("../buscar_plan_acad_cursos/?id_plan_academico="+id_plan_academico, "", function() {
                        $("#boton_agregar").show("slow");        
                    });
                } else {
                    $("#resul_plan_acad_cursos").hide("slow");
                    $("#boton_agregar").hide("slow");  
                 }
            });
        });
  </script>

templates/academico/plan_acad_curso/busq/busq_plan_acad_cursos.html
{% load staticfiles %}
 <table class="bordered">
              <tbody>
              {% for cic in ciclos %}
              <tr bgcolor="#74DF00">
                    <td colspan="8">Ciclo: <b>{{ cic.numero }} </b></td>
                </tr>
                <tr>
                    <th>Curso</th>
                    <th data-tooltip="Créditos" class="tooltipped">Cr</th>
                    <th data-tooltip="Horas presenciales" class="tooltipped">THP</th>
                    <th data-tooltip="Horas no presenciales"class="tooltipped">HNP</th> 
                    <th data-tooltip="Total Horas" class="tooltipped">TH</th>
                    <th colspan="2"></th>
                </tr>
               {% for planc in planes_acad_cursos %}
                {% if planc.ciclo == cic %}
				      <tr bgcolor="white"  onmouseover="this.style.backgroundColor='#EAECEE';"
                    onmouseout="this.style.backgroundColor='white';">
					          <td>
                        {{ planc.curso }} {% if planc.pre_requisito %}*{% endif %} 
                    </td>
                    <td>{{ planc.creditos }}</td>
                    <td>{{ planc.thp }}</td>
                    <td>{{ planc.hnp }}</td>
                    <td>{{ planc.total_horas }}</td>
                    <td align="center">
						          <a class="modal-editar"  href="#modal3" onclick="javascript:editar_plan_curso('{{ planc.id }}',''); void(0);">Editar</a>
					         </td>
					         <td align="center">
						          <a href="javascript:Eliminar_curso('{{ planc.id }}'); void(0);" data-position="top" data-delay="10" data-tooltip="Eliminar">Borrar</a>
					         </td>
				        </tr>
              {% endif %}
                {% endfor %}
               {% endfor %}
               </tbody>
            </table>

<script type="text/javascript">
    $('.modal-editar').leanModal();
</script>
<script src="{% static "js/init.js" %}"></script>

templates/academico/plan_acad_curso/busq/busq_pre_requisito.html
<div class="collection">
	{% for pre in planes_acad_cursos %}
    <a href="javascript:void(0);" class="collection-item"  onclick="Seleccionar_pre_curso('{{ pre.id }}','{{ pre.curso }}');">{{ pre.curso }}<span class="badge"><font size="1">Ciclo: {{ pre.ciclo }}</font></span></a>
    {% endfor %}
</div>

templates/academico/plan_acad_curso/busq/resul_eliminar_curso.html
<!-- <div class="chip">{{ resultado }} <i class="material-icons">close</i></div>-->
<script type="text/javascript">
        $(document).ready(function() {
                        var $toastContent = $('<span>{{ resultado }}</span>');
                            Materialize.toast($toastContent, 3000);
                    })
        </script>

templates/academico/plan_acad_curso/busq/resul_reg_curso.html
<div class="chip">{{ resultado }} <i class="material-icons">close</i></div>

templates/academico/plan_acad_curso/busq/resultado_agregar_plan_curso.html
<div class="chip">{{ resultado }} <i class="material-icons">close</i></div>